"""обновили коэффициент популярности

Revision ID: 61ee9260bf2b
Revises: 6e512b863602
Create Date: 2021-04-20 16:30:14.726553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ee9260bf2b'
down_revision = '6e512b863602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
