"""добавили коэффициент популяции

Revision ID: 6e512b863602
Revises: 
Create Date: 2021-04-20 16:21:43.579729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e512b863602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('coeff_popular', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'coeff_popular')
    # ### end Alembic commands ###
